set_run_state:
  fields:
    id:
      required: true
      example: "zm.example.com"
      selector:
        text:
    name:
      required: true
      example: "Home"
      selector:
        text:

ptz:
  target:
    entity:
      integration: zoneminder
      domain: camera
  fields:
    direction:
      required: true
      example: "right"
      selector:
        select:
          options:
            - "right"
            - "left"
            - "up"
            - "down"
            - "up_left"
            - "up_right"
            - "down_left"
            - "down_right"

ptz_preset:
  target:
    entity:
      integration: zoneminder
      domain: camera
  fields:
    preset:
      required: true
      example: "1"
      selector:
        number:
          min: 0
          max: 99
          mode: box
